apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: online-product
  name: online-product
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: online-product
status:
  loadBalancer: {}